export const TOGGLE_DEVICE = 'TOGGLE_DEVICE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SWITCH_EFFECT = 'SWITCH_EFFECT';

export const REFRESH_INTERVAL_AGENTS = 'REFRESH_INTERVAL_AGENTS';

export const REFRESH_INTERVAL_QUEUES = 'REFRESH_INTERVAL_QUEUES';

export const LOGGED_IN = 'LOGGED_IN';

export const ROUTER_REF = 'ROUTER_REF';